// AUTO-GENERATED by ts-server-fn. DO NOT EDIT.
import type { AddCommentRequest } from "../types/AddCommentRequest";
import type { CommentResponse } from "../types/CommentResponse";
import type { RoomPartition } from "../types/RoomPartition";
import { apiPost } from "../runtime/client";

export async function addComment(roomId: RoomPartition, after: string | null, req: AddCommentRequest): Promise<CommentResponse> {
  const __q = new URLSearchParams();
  if (after !== null && after !== undefined) __q.set("after", String(after));
  const __qs = __q.toString();
  const __url = `/api/rooms/${encodeURIComponent(String(roomId))}/comments` + (__qs ? `?${__qs}` : "");
  return apiPost<CommentResponse>(__url, { "req": req });
}
