//! Runtime support for the `ts-server-fn` proc-macro.
//!
//! A `proc-macro = true` crate can only export macros, so the items the
//! generated code references at runtime live here:
//!
//! - [`ApiRoute`] — one inventory entry per `#[get]/#[post]/...` handler.
//! - [`api_router`] — collects every registered route into an [`axum::Router`].
//! - [`AsStatusCode`] — implemented by your error enums; the generated
//!   response adapter calls it to map `Err(E)` → an HTTP status.
//! - a re-export of [`inventory`] so the macro can `inventory::submit!` without
//!   the consumer adding a direct dependency.
//!
//! ```ignore
//! // generated by the macro (illustrative):
//! ::ts_server_fn_axum::inventory::submit! {
//!     ::ts_server_fn_axum::ApiRoute {
//!         method: "GET",
//!         path: "/api/posts/{id}",
//!         register: |r| r.route("/api/posts/{id}", ::axum::routing::get(get_post)),
//!     }
//! }
//!
//! // your app:
//! let app = ts_server_fn_axum::api_router();
//! ```

pub use inventory;

use axum::http::StatusCode;
use axum::Router;

/// One registered route. The macro emits a non-capturing closure for
/// `register`, which coerces to this `fn` pointer.
pub struct ApiRoute {
    pub method: &'static str,
    pub path: &'static str,
    pub register: fn(Router) -> Router,
}

inventory::collect!(ApiRoute);

/// Map a domain error to an HTTP status. Implement for every error enum that
/// a `#[get]/#[post]/...` handler returns in its `Result<_, E>`.
pub trait AsStatusCode {
    fn as_status_code(&self) -> StatusCode;
}

/// Build a router from every inventory-registered [`ApiRoute`]. No hand-written
/// route table — every annotated handler is collected automatically.
pub fn api_router() -> Router {
    let mut router = Router::new();
    for route in inventory::iter::<ApiRoute> {
        router = (route.register)(router);
    }
    router
}

/// `(method, path)` for every registered route — for diagnostics and tests.
pub fn registered_routes() -> Vec<(&'static str, &'static str)> {
    inventory::iter::<ApiRoute>
        .into_iter()
        .map(|r| (r.method, r.path))
        .collect()
}
