//! Render a `HandlerMeta` into a TypeScript client function file.
//!
//! Output shape (PLAN.md §"생성 예"):
//!
//! ```typescript
//! // AUTO-GENERATED by ts-server-fn. DO NOT EDIT.
//! import type { GetMeResponse } from "../types/GetMeResponse";
//! import { apiGet } from "../runtime/client";
//!
//! export async function testHandler(): Promise<GetMeResponse> {
//!   return apiGet<GetMeResponse>("/api/test");
//! }
//! ```
//!
//! The generated function is a thin, typed wrapper over the hand-written
//! `runtime/client.ts` (`apiGet/apiPost/apiPut/apiPatch/apiDelete`). All
//! transport (base URL, `credentials: 'include'`, body wrapping,
//! status→throw) lives in that runtime, not here.

use std::collections::BTreeSet;

use convert_case::{Case, Casing};

use crate::route::{ArgKind, HandlerMeta};
use crate::tsgen::type_map::{imports_of, ts_type};

/// Result of rendering one handler.
pub struct RenderedTs {
    /// camelCase fn name, also used for the file stem (`<fnName>.ts`).
    pub fn_name_camel: String,
    /// The full `.ts` source.
    pub source: String,
}

/// HTTP method → runtime client fn + whether it carries a body.
fn runtime_fn(method: &str) -> (&'static str, bool) {
    match method {
        "GET" => ("apiGet", false),
        "POST" => ("apiPost", true),
        "PUT" => ("apiPut", true),
        "PATCH" => ("apiPatch", true),
        "DELETE" => ("apiDelete", false),
        _ => ("apiGet", false),
    }
}

/// Render the TS source for a single handler.
pub fn render(method: &str, meta: &HandlerMeta) -> RenderedTs {
    let fn_name_camel = meta.fn_name.to_case(Case::Camel);
    let (client_fn, carries_body) = runtime_fn(method);

    // ── Return type ──────────────────────────────────────────────────
    let ret_ts = meta
        .ret_ty
        .as_ref()
        .map(ts_type)
        .unwrap_or_else(|| "void".to_string());

    // ── Collect named-type imports (params + return) ─────────────────
    let mut named: BTreeSet<String> = BTreeSet::new();
    for a in &meta.client_args {
        imports_of(&a.ty, &mut named);
    }
    if let Some(rt) = &meta.ret_ty {
        imports_of(rt, &mut named);
    }

    // ── Parameter list (preserve declaration order) ──────────────────
    let params: Vec<String> = meta
        .client_args
        .iter()
        .map(|a| format!("{}: {}", a.name.to_string().to_case(Case::Camel), ts_type(&a.ty)))
        .collect();

    // Map original arg name → camelCase TS param name for URL/body refs.
    let camel = |s: &str| s.to_case(Case::Camel);

    // ── URL template literal ─────────────────────────────────────────
    // Substitute each `{}` in path_template with `${encodeURIComponent(arg)}`.
    let mut url = String::new();
    {
        let mut parts = meta.path_template.split("{}");
        if let Some(first) = parts.next() {
            url.push_str(first);
        }
        for (i, lit) in parts.enumerate() {
            let arg = &meta.path_args[i];
            url.push_str(&format!("${{encodeURIComponent(String({}))}}", camel(arg)));
            url.push_str(lit);
        }
    }

    // ── Query arg (a single `Query<T>` struct, if present) ───────────
    let query_arg = meta.client_args.iter().find(|a| a.kind == ArgKind::Query);

    // ── Body arg (a single `Json<T>` struct, for body-carrying methods)
    let body_arg = meta.client_args.iter().find(|a| a.kind == ArgKind::Body);

    // ── Compose function body ────────────────────────────────────────
    let mut body = String::new();

    if let Some(q) = query_arg {
        // Serialize the query struct generically: each own enumerable
        // property becomes `?k=v`, skipping null/undefined. The macro does
        // not know the struct's fields, so the object is walked at runtime.
        let cam = camel(&q.name.to_string());
        body.push_str("  const __q = new URLSearchParams();\n");
        body.push_str(&format!(
            "  for (const [__k, __v] of Object.entries(({cam} ?? {{}}) as Record<string, unknown>)) {{\n"
        ));
        body.push_str("    if (__v !== null && __v !== undefined) __q.set(__k, String(__v));\n  }\n");
        body.push_str(&format!(
            "  const __qs = __q.toString();\n  const __url = `{url}` + (__qs ? `?${{__qs}}` : \"\");\n"
        ));
    } else {
        body.push_str(&format!("  const __url = `{url}`;\n"));
    }

    // The runtime call. Body-carrying methods pass the request DTO directly
    // as the JSON body (axum `Json<T>` decodes the body as `T` itself — no
    // `{ "<argName>": <value> }` wrapping).
    let call = if carries_body {
        match body_arg {
            Some(a) => {
                let cam = camel(&a.name.to_string());
                format!("  return {client_fn}<{ret_ts}>(__url, {cam});\n")
            }
            None => format!("  return {client_fn}<{ret_ts}>(__url, undefined);\n"),
        }
    } else {
        format!("  return {client_fn}<{ret_ts}>(__url);\n")
    };
    body.push_str(&call);

    // ── Imports ──────────────────────────────────────────────────────
    let mut imports = String::new();
    for t in &named {
        // ts-rs emits one file per type at ../types/<TypeName>.ts
        imports.push_str(&format!("import type {{ {t} }} from \"../types/{t}\";\n"));
    }
    imports.push_str(&format!(
        "import {{ {client_fn} }} from \"../runtime/client\";\n"
    ));

    let param_list = params.join(", ");

    let source = format!(
        "// AUTO-GENERATED by ts-server-fn. DO NOT EDIT.\n\
         {imports}\n\
         export async function {fn_name_camel}({param_list}): Promise<{ret_ts}> {{\n\
         {body}}}\n"
    );

    RenderedTs {
        fn_name_camel,
        source,
    }
}
