//! Render a `HandlerMeta` into a TypeScript client function file.
//!
//! Output (D2 — request body is the DTO itself, no `{ "<arg>": value }`
//! wrapping; query is the `Query<T>` struct passed as an object):
//!
//! ```typescript
//! // AUTO-GENERATED by ts-server-fn. DO NOT EDIT.
//! import type { PostResponse } from "../types/PostResponse";
//! import type { CreatePostRequest } from "../types/CreatePostRequest";
//! import { apiPost } from "../runtime/client";
//!
//! export async function createPost(body: CreatePostRequest): Promise<PostResponse> {
//!   return apiPost<PostResponse>(`/api/posts`, body);
//! }
//! ```
//!
//! Transport (base URL, `credentials: 'include'`, status→throw, querystring
//! building, 204→void) lives in the hand-written `runtime/client.ts`. The
//! generated fn only builds the URL and forwards the body/query objects.

use std::collections::BTreeSet;

use convert_case::{Case, Casing};

use crate::route::{ArgKind, HandlerMeta};
use crate::tsgen::type_map::{imports_of, ts_type};

pub struct RenderedTs {
    pub fn_name_camel: String,
    pub source: String,
}

/// (runtime fn, carries-body).
fn runtime_fn(method: &str) -> (&'static str, bool) {
    match method {
        "GET" => ("apiGet", false),
        "POST" => ("apiPost", true),
        "PUT" => ("apiPut", true),
        "PATCH" => ("apiPatch", true),
        "DELETE" => ("apiDelete", false),
        _ => ("apiGet", false),
    }
}

pub fn render(method: &str, meta: &HandlerMeta) -> RenderedTs {
    let fn_name_camel = meta.fn_name.to_case(Case::Camel);
    let (client_fn, carries_body) = runtime_fn(method);
    let camel = |s: &str| s.to_case(Case::Camel);

    let ret_ts = meta
        .ret_ty
        .as_ref()
        .map(ts_type)
        .unwrap_or_else(|| "void".to_string());

    // ── named-type imports (params + success return; NOT the error type,
    //    which is only referenced in a doc comment) ─────────────────────
    let mut named: BTreeSet<String> = BTreeSet::new();
    for a in &meta.client_args {
        imports_of(&a.ty, &mut named);
    }
    if let Some(rt) = &meta.ret_ty {
        imports_of(rt, &mut named);
    }

    // ── params, in path → query → body order ──────────────────────────
    let params: Vec<String> = meta
        .client_args
        .iter()
        .map(|a| format!("{}: {}", camel(&a.name), ts_type(&a.ty)))
        .collect();

    // ── URL template literal (interpolate path args positionally) ─────
    let mut url = String::new();
    let mut parts = meta.path_template.split("{}");
    if let Some(first) = parts.next() {
        url.push_str(first);
    }
    for (i, lit) in parts.enumerate() {
        let arg = meta
            .path_names
            .get(i)
            .cloned()
            .unwrap_or_else(|| format!("arg{i}"));
        url.push_str(&format!("${{encodeURIComponent(String({}))}}", camel(&arg)));
        url.push_str(lit);
    }

    let query_name = meta
        .client_args
        .iter()
        .find(|a| a.kind == ArgKind::Query)
        .map(|a| camel(&a.name));
    let body_name = meta
        .client_args
        .iter()
        .find(|a| a.kind == ArgKind::Body)
        .map(|a| camel(&a.name));

    // ── runtime call ──────────────────────────────────────────────────
    let mut call_args = vec![format!("`{url}`")];
    if carries_body {
        call_args.push(body_name.clone().unwrap_or_else(|| "undefined".into()));
        if let Some(q) = &query_name {
            call_args.push(q.clone());
        }
    } else if let Some(q) = &query_name {
        call_args.push(q.clone());
    }
    let call = format!(
        "  return {client_fn}<{ret_ts}>({});\n",
        call_args.join(", ")
    );

    // ── imports ───────────────────────────────────────────────────────
    let mut imports = String::new();
    for t in &named {
        imports.push_str(&format!("import type {{ {t} }} from \"../types/{t}\";\n"));
    }
    imports.push_str(&format!("import {{ {client_fn} }} from \"../runtime/client\";\n"));

    // ── error doc (Risk #2: surface the error body type when known) ───
    let err_doc = match &meta.err_ty {
        Some(e) => format!("/** @throws ApiError — non-2xx body is `{}`. */\n", ts_type(e)),
        None => String::new(),
    };

    let source = format!(
        "// AUTO-GENERATED by ts-server-fn. DO NOT EDIT.\n\
         {imports}\n\
         {err_doc}export async function {fn_name_camel}({}): Promise<{ret_ts}> {{\n\
         {call}}}\n",
        params.join(", ")
    );

    RenderedTs {
        fn_name_camel,
        source,
    }
}
